services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ginrummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/ginrummy"
      JWT_SECRET: "dev-jwt-secret-change-in-production"
      JWT_REFRESH_SECRET: "dev-refresh-secret-change-in-production"
      NODE_ENV: "production"
      PORT: 3001
      CORS_ORIGIN: "http://localhost:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/api/prisma:/app/apps/api/prisma
    command: sh -c "pnpm db:deploy && pnpm db:seed && pnpm start"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: "http://localhost:3001"
    depends_on:
      - api

volumes:
  postgres_data: